version: '5.0'

actions:

# covid: wave_1
  extract_covid_wave_1:
    run: ehrql:v1 generate-dataset analysis/1-extract/dataset_definition.py
      --output output/1-extract/extract_covid_wave_1.arrow
      --dummy-data-file analysis/1-extract/dummy-data/dummy_covid_wave_1.arrow
      --
      --cohort_id covid_wave_1
    outputs:
      highly_sensitive:
        cohort: output/1-extract/extract_covid_wave_1.arrow

  prepare_covid_wave_1:
    run: r:v2 analysis/2-prepare/prepare.R covid_wave_1
    needs: [extract_covid_wave_1]
    outputs:
      highly_sensitive:
        cohort: output/2-prepare/prepare_covid_wave_1/prepare_covid_wave_1.arrow
      moderately_sensitive:
        txt: output/2-prepare/prepare_covid_wave_1/*.txt

  report_covid_wave_1:
    run: r:v2 analysis/3-report/report_cohort.R covid_wave_1
    needs: [prepare_covid_wave_1]
    outputs:
      moderately_sensitive:
        csv: output/3-report/report_covid_wave_1/*.csv
        png: output/3-report/report_covid_wave_1/*.png
        txt: output/3-report/report_covid_wave_1/*.txt


# covid: ba1_ba2
  extract_covid_ba1_ba2:
    run: ehrql:v1 generate-dataset analysis/1-extract/dataset_definition.py
      --output output/1-extract/extract_covid_ba1_ba2.arrow
      --dummy-data-file analysis/1-extract/dummy-data/dummy_covid_ba1_ba2.arrow
      --
      --cohort_id covid_ba1_ba2
    outputs:
      highly_sensitive:
        cohort: output/1-extract/extract_covid_ba1_ba2.arrow

  prepare_covid_ba1_ba2:
    run: r:v2 analysis/2-prepare/prepare.R covid_ba1_ba2
    needs: [extract_covid_ba1_ba2]
    outputs:
      highly_sensitive:
        cohort: output/2-prepare/prepare_covid_ba1_ba2/prepare_covid_ba1_ba2.arrow
      moderately_sensitive:
        txt: output/2-prepare/prepare_covid_ba1_ba2/*.txt

  report_covid_ba1_ba2:
    run: r:v2 analysis/3-report/report_cohort.R covid_ba1_ba2
    needs: [prepare_covid_ba1_ba2]
    outputs:
      moderately_sensitive:
        csv: output/3-report/report_covid_ba1_ba2/*.csv
        png: output/3-report/report_covid_ba1_ba2/*.png
        txt: output/3-report/report_covid_ba1_ba2/*.txt


# covid: jn1
  extract_covid_jn1:
    run: ehrql:v1 generate-dataset analysis/1-extract/dataset_definition.py
      --output output/1-extract/extract_covid_jn1.arrow
      --dummy-data-file analysis/1-extract/dummy-data/dummy_covid_jn1.arrow
      --
      --cohort_id covid_jn1
    outputs:
      highly_sensitive:
        cohort: output/1-extract/extract_covid_jn1.arrow

  prepare_covid_jn1:
    run: r:v2 analysis/2-prepare/prepare.R covid_jn1
    needs: [extract_covid_jn1]
    outputs:
      highly_sensitive:
        cohort: output/2-prepare/prepare_covid_jn1/prepare_covid_jn1.arrow
      moderately_sensitive:
        txt: output/2-prepare/prepare_covid_jn1/*.txt

  report_covid_jn1:
    run: r:v2 analysis/3-report/report_cohort.R covid_jn1
    needs: [prepare_covid_jn1]
    outputs:
      moderately_sensitive:
        csv: output/3-report/report_covid_jn1/*.csv
        png: output/3-report/report_covid_jn1/*.png
        txt: output/3-report/report_covid_jn1/*.txt


# covid: 2025_26
  extract_covid_2025_26:
    run: ehrql:v1 generate-dataset analysis/1-extract/dataset_definition.py
      --output output/1-extract/extract_covid_2025_26.arrow
      --dummy-data-file analysis/1-extract/dummy-data/dummy_covid_2025_26.arrow
      --
      --cohort_id covid_2025_26
    outputs:
      highly_sensitive:
        cohort: output/1-extract/extract_covid_2025_26.arrow

  prepare_covid_2025_26:
    run: r:v2 analysis/2-prepare/prepare.R covid_2025_26
    needs: [extract_covid_2025_26]
    outputs:
      highly_sensitive:
        cohort: output/2-prepare/prepare_covid_2025_26/prepare_covid_2025_26.arrow
      moderately_sensitive:
        txt: output/2-prepare/prepare_covid_2025_26/*.txt

  report_covid_2025_26:
    run: r:v2 analysis/3-report/report_cohort.R covid_2025_26
    needs: [prepare_covid_2025_26]
    outputs:
      moderately_sensitive:
        csv: output/3-report/report_covid_2025_26/*.csv
        png: output/3-report/report_covid_2025_26/*.png
        txt: output/3-report/report_covid_2025_26/*.txt


# flu: 2023_24
  extract_flu_2023_24:
    run: ehrql:v1 generate-dataset analysis/1-extract/dataset_definition.py
      --output output/1-extract/extract_flu_2023_24.arrow
      --dummy-data-file analysis/1-extract/dummy-data/dummy_flu_2023_24.arrow
      --
      --cohort_id flu_2023_24
    outputs:
      highly_sensitive:
        cohort: output/1-extract/extract_flu_2023_24.arrow

  prepare_flu_2023_24:
    run: r:v2 analysis/2-prepare/prepare.R flu_2023_24
    needs: [extract_flu_2023_24]
    outputs:
      highly_sensitive:
        cohort: output/2-prepare/prepare_flu_2023_24/prepare_flu_2023_24.arrow
      moderately_sensitive:
        txt: output/2-prepare/prepare_flu_2023_24/*.txt

  report_flu_2023_24:
    run: r:v2 analysis/3-report/report_cohort.R flu_2023_24
    needs: [prepare_flu_2023_24]
    outputs:
      moderately_sensitive:
        csv: output/3-report/report_flu_2023_24/*.csv
        png: output/3-report/report_flu_2023_24/*.png
        txt: output/3-report/report_flu_2023_24/*.txt


# flu: 2024_25
  extract_flu_2024_25:
    run: ehrql:v1 generate-dataset analysis/1-extract/dataset_definition.py
      --output output/1-extract/extract_flu_2024_25.arrow
      --dummy-data-file analysis/1-extract/dummy-data/dummy_flu_2024_25.arrow
      --
      --cohort_id flu_2024_25
    outputs:
      highly_sensitive:
        cohort: output/1-extract/extract_flu_2024_25.arrow

  prepare_flu_2024_25:
    run: r:v2 analysis/2-prepare/prepare.R flu_2024_25
    needs: [extract_flu_2024_25]
    outputs:
      highly_sensitive:
        cohort: output/2-prepare/prepare_flu_2024_25/prepare_flu_2024_25.arrow
      moderately_sensitive:
        txt: output/2-prepare/prepare_flu_2024_25/*.txt

  report_flu_2024_25:
    run: r:v2 analysis/3-report/report_cohort.R flu_2024_25
    needs: [prepare_flu_2024_25]
    outputs:
      moderately_sensitive:
        csv: output/3-report/report_flu_2024_25/*.csv
        png: output/3-report/report_flu_2024_25/*.png
        txt: output/3-report/report_flu_2024_25/*.txt


# flu: 2025_26
  extract_flu_2025_26:
    run: ehrql:v1 generate-dataset analysis/1-extract/dataset_definition.py
      --output output/1-extract/extract_flu_2025_26.arrow
      --dummy-data-file analysis/1-extract/dummy-data/dummy_flu_2025_26.arrow
      --
      --cohort_id flu_2025_26
    outputs:
      highly_sensitive:
        cohort: output/1-extract/extract_flu_2025_26.arrow

  prepare_flu_2025_26:
    run: r:v2 analysis/2-prepare/prepare.R flu_2025_26
    needs: [extract_flu_2025_26]
    outputs:
      highly_sensitive:
        cohort: output/2-prepare/prepare_flu_2025_26/prepare_flu_2025_26.arrow
      moderately_sensitive:
        txt: output/2-prepare/prepare_flu_2025_26/*.txt

  report_flu_2025_26:
    run: r:v2 analysis/3-report/report_cohort.R flu_2025_26
    needs: [prepare_flu_2025_26]
    outputs:
      moderately_sensitive:
        csv: output/3-report/report_flu_2025_26/*.csv
        png: output/3-report/report_flu_2025_26/*.png
        txt: output/3-report/report_flu_2025_26/*.txt


# rsv: 2023_24
  extract_rsv_2023_24:
    run: ehrql:v1 generate-dataset analysis/1-extract/dataset_definition.py
      --output output/1-extract/extract_rsv_2023_24.arrow
      --dummy-data-file analysis/1-extract/dummy-data/dummy_rsv_2023_24.arrow
      --
      --cohort_id rsv_2023_24
    outputs:
      highly_sensitive:
        cohort: output/1-extract/extract_rsv_2023_24.arrow

  prepare_rsv_2023_24:
    run: r:v2 analysis/2-prepare/prepare.R rsv_2023_24
    needs: [extract_rsv_2023_24]
    outputs:
      highly_sensitive:
        cohort: output/2-prepare/prepare_rsv_2023_24/prepare_rsv_2023_24.arrow
      moderately_sensitive:
        txt: output/2-prepare/prepare_rsv_2023_24/*.txt

  report_rsv_2023_24:
    run: r:v2 analysis/3-report/report_cohort.R rsv_2023_24
    needs: [prepare_rsv_2023_24]
    outputs:
      moderately_sensitive:
        csv: output/3-report/report_rsv_2023_24/*.csv
        png: output/3-report/report_rsv_2023_24/*.png
        txt: output/3-report/report_rsv_2023_24/*.txt


# rsv: 2024_25
  extract_rsv_2024_25:
    run: ehrql:v1 generate-dataset analysis/1-extract/dataset_definition.py
      --output output/1-extract/extract_rsv_2024_25.arrow
      --dummy-data-file analysis/1-extract/dummy-data/dummy_rsv_2024_25.arrow
      --
      --cohort_id rsv_2024_25
    outputs:
      highly_sensitive:
        cohort: output/1-extract/extract_rsv_2024_25.arrow

  prepare_rsv_2024_25:
    run: r:v2 analysis/2-prepare/prepare.R rsv_2024_25
    needs: [extract_rsv_2024_25]
    outputs:
      highly_sensitive:
        cohort: output/2-prepare/prepare_rsv_2024_25/prepare_rsv_2024_25.arrow
      moderately_sensitive:
        txt: output/2-prepare/prepare_rsv_2024_25/*.txt

  report_rsv_2024_25:
    run: r:v2 analysis/3-report/report_cohort.R rsv_2024_25
    needs: [prepare_rsv_2024_25]
    outputs:
      moderately_sensitive:
        csv: output/3-report/report_rsv_2024_25/*.csv
        png: output/3-report/report_rsv_2024_25/*.png
        txt: output/3-report/report_rsv_2024_25/*.txt


# rsv: 2025_26
  extract_rsv_2025_26:
    run: ehrql:v1 generate-dataset analysis/1-extract/dataset_definition.py
      --output output/1-extract/extract_rsv_2025_26.arrow
      --dummy-data-file analysis/1-extract/dummy-data/dummy_rsv_2025_26.arrow
      --
      --cohort_id rsv_2025_26
    outputs:
      highly_sensitive:
        cohort: output/1-extract/extract_rsv_2025_26.arrow

  prepare_rsv_2025_26:
    run: r:v2 analysis/2-prepare/prepare.R rsv_2025_26
    needs: [extract_rsv_2025_26]
    outputs:
      highly_sensitive:
        cohort: output/2-prepare/prepare_rsv_2025_26/prepare_rsv_2025_26.arrow
      moderately_sensitive:
        txt: output/2-prepare/prepare_rsv_2025_26/*.txt

  report_rsv_2025_26:
    run: r:v2 analysis/3-report/report_cohort.R rsv_2025_26
    needs: [prepare_rsv_2025_26]
    outputs:
      moderately_sensitive:
        csv: output/3-report/report_rsv_2025_26/*.csv
        png: output/3-report/report_rsv_2025_26/*.png
        txt: output/3-report/report_rsv_2025_26/*.txt